main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
depend: [DiscordSRV]
version: ${project.version}
author: VapoR
commands:
  btel-reload:
    description: Reload plugin
    usage: /btel-reload
    permission: btel.admin.reload
  btel-sync:
    description: Runs website -> Discord sync
    usage: /btel-sync
    permission: btel.admin.sync
permissions:
  btel.*:
    description: Wildcard
    children:
      btel.admin: true
      btel.admin.reload: true
      btel.admin.sync: true
  btel.admin.*:
    description: Admin wildcard
    children:
      btel.admin.reload: true
      btel.admin.sync: true
  btel.admin.reload:
    description: Allows usage of /btel-reload
  btel.admin.sync:
    description: Allows usage of /btel-sync
